In [1]:
# import from src
from src.Model import Model
from src.Convolution import Convolution
from src.Dense import Dense
from src.Pooling import Pooling
from src.Flatten import Flatten
from src.LSTM import LSTM


In [2]:
import numpy as np

## Test From PPT

In [3]:
input = np.array([[1,2],[0.5,3]])
# input = np.array([[1,2]])
weight_forget_u = np.array(
    [0.7,0.45]
    )
weight_input_u = np.array(
    [0.95,0.8]
    )
weight_cell_u= np.array(
    [0.45,0.25]
    )
weight_output_u= np.array(
    [0.6,0.4]
    )

weight_forget = np.array(
    [0.1]
    )
weight_input = np.array(
    [0.8]
    )
weight_cell= np.array(
    [0.15]
    )
weight_output= np.array(
    [0.25]
    )

bias_forget = np.array(
    [0.15]
    )
bias_input = np.array(
    [0.65]
    )
bias_cell= np.array(
    [0.2]
    )
bias_output= np.array(
    [0.1]
    )

input_shape = input.shape[1]
input.shape[1]

2

In [4]:
lstm_model = LSTM(input_size=input_shape,num_units=1)
lstm_model.set_weight_input('forget', weight_forget_u)
lstm_model.set_weight_input('input', weight_input_u)
lstm_model.set_weight_input('cell',weight_cell_u)
lstm_model.set_weight_input('output',weight_output_u)

lstm_model.set_weight_hidden('forget', weight_forget)
lstm_model.set_weight_hidden('input', weight_input)
lstm_model.set_weight_hidden('cell',weight_cell)
lstm_model.set_weight_hidden('output',weight_output)

lstm_model.set_bias('forget', bias_forget)
lstm_model.set_bias('input', bias_input)
lstm_model.set_bias('cell',bias_cell)
lstm_model.set_bias('output',bias_output)

In [5]:
model = Model()
model.add(lstm_model)


In [6]:
result = model.predict(input)

[0.8519528]
[0.96083428]
[0.81775408]
[0.81757448]
[0.87030197]
[0.98118397]
[0.84980402]
[0.84993334]


In [7]:
result

array([[[[0.78572615]],

        [[0.5363134 ]]],


       [[[1.5176331 ]],

        [[0.77198111]]]])

In [8]:
input = np.array([[1,2],[0.5,3]])


input_size = input.shape[1]
input.shape[1]

2

In [9]:
model = Model()
model.add(LSTM(input_size=input_size,num_units=2))

## Test Num units > 1

In [10]:
result = model.predict(input)
result

[[0.86732503 0.62272291]]
[[0.86456248 0.52069864]]
[[0.35900411 0.96073142]]
[[0.69432128 0.67012019]]
[[0.90054513 0.67610438]]
[[0.9235432  0.62893852]]
[[0.58526692 0.98673626]]
[[0.76724572 0.69694174]]


array([[[[0.31038148, 0.50025154]],

        [[0.20884081, 0.30980659]]],


       [[[0.82003181, 0.9588187 ]],

        [[0.51795776, 0.51835006]]]])

In [11]:
A = Model.loadModel("model_4_parameters.json")

len U:  (64, 64) (64, 64) (64, 64) (64, 64)
len weight:  (5, 64) (5, 64) (5, 64) (5, 64)
len bias:  (64,) (64,) (64,) (64,)
64
kernel 64
bias 5
