In [1]:
# import from src
from src.Model import Model
from src.Convolution import Convolution
from src.Dense import Dense
from src.Pooling import Pooling
from src.Flatten import Flatten
from src.LSTM import LSTM


In [2]:
import numpy as np

## Test From PPT

In [3]:
input = np.array([[1,2],[0.5,3]])
# input = np.array([[1,2]])
weight_forget = np.array(
    [0.7,0.45,0.1]
    )
weight_input = np.array(
    [0.95,0.8,0.8]
    )
weight_cell= np.array(
    [0.45,0.25,0.15]
    )
weight_output= np.array(
    [0.6,0.4,0.25]
    )

bias_forget = np.array(
    [0.15]
    )
bias_input = np.array(
    [0.65]
    )
bias_cell= np.array(
    [0.2]
    )
bias_output= np.array(
    [0.1]
    )

input_shape = input.shape[1]
input.shape[1]

2

In [4]:
lstm_model = LSTM(input_size=input_shape,num_units=1)
lstm_model.set_weight('forget', weight_forget)
lstm_model.set_weight('input', weight_input)
lstm_model.set_weight('cell',weight_cell)
lstm_model.set_weight('output',weight_output)
lstm_model.set_bias('forget', bias_forget)
lstm_model.set_bias('input', bias_input)
lstm_model.set_bias('cell',bias_cell)
lstm_model.set_bias('output',bias_output)

In [5]:
model = Model()
model.add(lstm_model)


In [6]:
result = model.predict(input)

[0.8519528]
[0.96083428]
[0.81775408]
[0.81757448]
[0.87030197]
[0.98118397]
[0.84980402]
[0.84993334]


In [7]:
result

array([[[[0.78572615]],

        [[0.5363134 ]]],


       [[[1.5176331 ]],

        [[0.77198111]]]])

In [8]:
input = np.array([[1,2],[0.5,3]])


input_size = input.shape[1]
input.shape[1]

2

In [9]:
model = Model()
model.add(LSTM(input_size=input_size,num_units=2))

## Test Num units > 1

In [10]:
result = model.predict(input)
result

[[0.92630032 0.85154089]]
[[0.80591526 0.88302913]]
[[0.88895758 0.69253465]]
[[0.85838326 0.60627726]]
[[0.97167628 0.93937949]]
[[0.94072545 0.96953742]]
[[0.9870134  0.85619386]]
[[0.93625344 0.71975297]]


array([[[[0.71642448, 0.61152827]],

        [[0.52763931, 0.33054357]]],


       [[[1.6246413 , 1.4045691 ]],

        [[0.8663103 , 0.63794245]]]])