In [1]:
# import from src
from src.Model import Model
from src.Convolution import Convolution
from src.Dense import Dense
from src.Pooling import Pooling
from src.Flatten import Flatten
from src.LSTM import LSTM


In [2]:
import numpy as np

## Test From PPT

In [3]:
input = np.array([[[1,2], [0.5,3]]])

weight_forget_u = np.array(
    [0.7,0.45]
    )
weight_input_u = np.array(
    [0.95,0.8]
    )
weight_cell_u= np.array(
    [0.45,0.25]
    )
weight_output_u= np.array(
    [0.6,0.4]
    )

weight_forget = np.array(
    [0.1]
    )
weight_input = np.array(
    [0.8]
    )
weight_cell= np.array(
    [0.15]
    )
weight_output= np.array(
    [0.25]
    )

bias_forget = np.array(
    [0.15]
    )
bias_input = np.array(
    [0.65]
    )
bias_cell= np.array(
    [0.2]
    )
bias_output= np.array(
    [0.1]
    )


In [4]:
sequence_length = 1
num_feature = 2
input_shape = (sequence_length, num_feature)
lstm_model = LSTM(input_shape=input_shape,num_units=1)

In [5]:
lstm_model.set_weight_input('forget', weight_forget_u)
lstm_model.set_weight_input('input', weight_input_u)
lstm_model.set_weight_input('cell',weight_cell_u)
lstm_model.set_weight_input('output',weight_output_u)

lstm_model.set_weight_hidden('forget', weight_forget)
lstm_model.set_weight_hidden('input', weight_input)
lstm_model.set_weight_hidden('cell',weight_cell)
lstm_model.set_weight_hidden('output',weight_output)

lstm_model.set_bias('forget', bias_forget)
lstm_model.set_bias('input', bias_input)
lstm_model.set_bias('cell',bias_cell)
lstm_model.set_bias('output',bias_output)

In [6]:
model = Model()
model.add(lstm_model)


In [7]:
result = model.predict(input)

In [8]:
result

array([[0.77198111]])

## Test Num feature and sequence > 1

In [9]:
num_samples = 2
sequence_length = 2
num_feature = 3
input_shape = (sequence_length, num_feature)
input_2 = np.random.rand(num_samples, sequence_length , num_feature)


In [10]:
lstm_mod = LSTM(input_shape=input_shape,num_units=64)
# lstm_mod.print_state()
model_2 = Model()
model_2.add(lstm_mod )

In [11]:
result = model_2.predict(input_2)
result

array([[0.8623178 , 0.84740265, 0.78548661, 0.82522749, 0.86034527,
        0.85786521, 0.86683904, 0.87855045, 0.86299416, 0.87067142,
        0.80205482, 0.8219219 , 0.85907367, 0.85965785, 0.8557149 ,
        0.88116216, 0.85084955, 0.86920556, 0.87756336, 0.88487984,
        0.88344913, 0.79580901, 0.86710414, 0.86757118, 0.80073516,
        0.88904234, 0.79399986, 0.88118354, 0.85158381, 0.90140667,
        0.84991203, 0.85271084, 0.80958602, 0.84141895, 0.88285048,
        0.87353004, 0.82589715, 0.88480627, 0.85463057, 0.79397705,
        0.86785757, 0.83664107, 0.84577172, 0.82994337, 0.88589262,
        0.88373312, 0.82821367, 0.89701949, 0.84874874, 0.85681454,
        0.86476395, 0.82156537, 0.81615191, 0.85058983, 0.81139879,
        0.82289931, 0.86864412, 0.84887949, 0.86879052, 0.87006361,
        0.85587723, 0.78779152, 0.86269723, 0.88538484],
       [0.88998809, 0.86332113, 0.80649551, 0.86490249, 0.89802422,
        0.86191813, 0.87462752, 0.87984502, 0.85233703, 0.8

## Load Model

terdapat perbedaan pada model yang diberikan di spesifikasi dimana pada model yang kami buat, kami mengikuti PPT power point dimana variabel U merupakan weight untuk input sedangkan variabel W merupakan variabel untuk hidden.

In [12]:
model_load = Model.loadModel("model_4_parameters.json")

In [13]:
num_samples = 2
num_timesteps = 4
num_features = 5
input = np.random.rand(num_samples, num_timesteps, num_features)

In [15]:
result = model_load.predict(input)
result

array([[0.56395982, 1.48678868, 0.        , 0.        , 1.23031444],
       [0.81804762, 1.86540155, 0.        , 0.        , 1.70384106]])

## Using Keras

In [16]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

# Example multivariate time series data (shape: num_samples, num_timesteps, num_features)
num_samples = 1
num_timesteps = 10
num_features = 3
input_data = np.random.rand(num_samples, num_timesteps, num_features)

# Define LSTM model
model = Sequential()

# LSTM layer with 50 units (you can adjust the number of units as needed)
model.add(LSTM(64, input_shape=(num_timesteps, num_features)))

# Output layer (example: regression task with 1 output neuron)
model.add(Dense(5))

# Compile the model (you can change the loss and optimizer based on your task)
model.compile(loss='mean_squared_error', optimizer='adam')

# Print model summary
model.summary()

# Perform a forward pass with the input data
predictions = model.predict(input_data)

# Print the shape of predictions (num_samples, 1) for a regression task with 1 output neuron
print("Predictions shape:", predictions.shape)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 64)                17408     
                                                                 
 dense (Dense)               (None, 5)                 325       
                                                                 
Total params: 17733 (69.27 KB)
Trainable params: 17733 (69.27 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
1/1 [==============================] - 0s 385ms/step
Predictions shape: (1, 5)
